---

- name: default policies
  shell: iptables -P {{item | upper}} {{ firewall_policies[item] | default('ACCEPT') }}
  with_items:
    - input
    - output
    - forward

- name: default policies
  shell: ip6tables -P {{item | upper}} {{ firewall_policies[item] | default('ACCEPT') }}
  with_items:
    - input
    - output
    - forward
